### ISSUE TITLE
Use additional honeycomb env variables

### ISSUE THREAD

**Issue by Fishrock123** [eaze/preroll#6]
In additional to `HONEYCOMBIO_WRITE_KEY` we should also listen to these, similar to Botlzmann:
- [x] `HONEYCOMBIO_DATASET`
- [x] ~~`HONEYCOMBIO_TEAM`~~
- [ ] `HONEYCOMBIO_SAMPLE_RATE` (depends on https://github.com/eaze/preroll/issues/7)

**Comment by jtthackery** [comment]
We should also add support for `HONEYCOMB_API_HOST`, to enable using a proxy (like refinery).  It looks like it's supported by libhoney: https://docs.rs/libhoney-rust/0.1.6/libhoney/client/struct.Options.html#structfield.api_host

**Comment by Fishrock123** [comment]
`HONEYCOMB_SAMPLE_RATE` done in 82b3ad19e8f2ddfb97147ed816c21b577fdbb52b
`HONEYCOMB_API_HOST` done in 19ce55af5a29ea672954581130bd7c76006f9596

Moved to `HONEYCOMB_` without the `IO` in env vars in d6634d2b3c8760b3ecc621d02ff19dc66d35ba7d
